# Generated by Django 5.0.6 on 2024-06-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=50)),
                ('scripcode', models.CharField(max_length=50)),
            ],
        ),
    ]
