# Generated by Django 5.0.6 on 2024-06-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0003_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date',
            field=models.DateTimeField(default='<function now at 0x0000014E7CE90860>'),
        ),
    ]
